# Objetos Python

## Arrays

In [1]:
import numpy as np

- *Devemos garantir que os arrays numpy possuem a **mesma quantidade de elementos** e que sejam do **mesmo tipo de dado**!*

In [2]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
a.shape

(2, 4)

In [4]:
a[1,3]

7

In [5]:
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [6]:
a[1]

array([4, 5, 8, 7])

- *Um array numpy **bidimensional** é considerado uma **matriz**.*

In [7]:
import random

In [8]:
prob = random.random()
print(prob)

0.6180789751429727


In [9]:
num = random.randint(1,8)
num

4

In [10]:
# Comando para criar uma matriz de 4 linhas e 6 colunas
np.random.randint(1,6,(4,6))

array([[3, 3, 5, 1, 2, 5],
       [4, 4, 5, 1, 2, 3],
       [2, 2, 4, 1, 3, 3],
       [1, 1, 2, 4, 2, 2]])